![Imgur](https://i.imgur.com/5pXzCIu.png)

# Data Science va Sun'iy Intellekt Praktikum

## 5-MODUL. Machine Learning

### Portfolio uchun vazifa: Toshkent shahrida uylarning narxini aniqlash.

Ushbu amaliyotda sizning vazifangiz berilgan ma`lumotlar asosida Toshkent shahridagi uylarning narxini aniqlash.

In [ ]:
import pandas as pd
import numpy as np
df = pd.read_csv('https://raw.githubusercontent.com/anvarnarz/praktikum_datasets/main/housing_data_08-02-2021.csv')
df.head()

location       district  rooms  \
0  город Ташкент, Юнусабадский район, Юнусабад 8-...   Юнусабадский      3   
1  город Ташкент, Яккасарайский район, 1-й тупик ...  Яккасарайский      2   
2  город Ташкент, Чиланзарский район, Чиланзар 2-...   Чиланзарский      2   
3  город Ташкент, Чиланзарский район, Чиланзар 9-...   Чиланзарский      3   
4  город Ташкент, Чиланзарский район, площадь Актепа   Чиланзарский      3   

  size  level  max_levels  price  
0   57      4           4  52000  
1   52      4           5  56000  
2   42      4           4  37000  
3   65      1           4  49500  
4   70      3           5  55000

# Ustunlar ta'rifi
- `location` - sotilayotgan uy manzili
- `district` - uy joylashgan tuman
- `rooms` - xonalar soni
- `size` - uy maydoni (kv.m)
- `level` - uy joylashgan qavat
- `max_levels` - ja'mi qavatlar soni
- `price` - uy narxi

## Vazifani CRSIP-DM Metolodgiyasi yordamida bajaring.
<img src="https://i.imgur.com/dzZnnYi.png" alt="CRISP-DM" width="800"/>

# Malumotlarni tahlil qilamiz

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7565 entries, 0 to 7564
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   location    7565 non-null   object
 1   district    7565 non-null   object
 2   rooms       7565 non-null   int64 
 3   size        7565 non-null   object
 4   level       7565 non-null   int64 
 5   max_levels  7565 non-null   int64 
 6   price       7565 non-null   object
dtypes: int64(3), object(4)
memory usage: 413.8+ KB


In [ ]:
df.isnull().sum()

location      0
district      0
rooms         0
size          0
level         0
max_levels    0
price         0
dtype: int64

In [ ]:
df['size'] = df['size'].astype(float)

ValueError: could not convert string to float: 'Площадьземли:1сот'

In [ ]:
df[df['size']== 'Площадьземли:1сот']

location     district  rooms  \
5347  город Ташкент, Яшнободский район, Дархон  Яшнободский      4   

                   size  level  max_levels   price  
5347  Площадьземли:1сот      3           5  150000

In [ ]:
df.loc[5347,'size'] = np.nan

In [ ]:
df['size'] = df['size'].astype(float)

In [ ]:
df.price = df.price.astype(float)

ValueError: could not convert string to float: 'Договорная'

In [ ]:
df.loc[df[df['price']=='Договорная'].index,'price'] = np.nan

In [ ]:
df.price = df.price.astype(float)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7565 entries, 0 to 7564
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   location    7565 non-null   object 
 1   district    7565 non-null   object 
 2   rooms       7565 non-null   int64  
 3   size        7564 non-null   float64
 4   level       7565 non-null   int64  
 5   max_levels  7565 non-null   int64  
 6   price       7466 non-null   float64
dtypes: float64(2), int64(3), object(2)
memory usage: 413.8+ KB


In [ ]:
df.describe()

rooms          size        level   max_levels         price
count  7565.000000   7564.000000  7565.000000  7565.000000  7.466000e+03
mean      2.625644    113.268990     3.699273     6.038202  7.133421e+04
std       1.085201   1491.312092     2.237275     2.613271  6.405237e+05
min       1.000000      1.000000     1.000000     1.000000  2.000000e+00
25%       2.000000     50.000000     2.000000     4.000000  3.500000e+04
50%       3.000000     66.000000     3.000000     5.000000  4.650000e+04
75%       3.000000     86.000000     5.000000     9.000000  6.700000e+04
max      10.000000  70000.000000    19.000000    25.000000  5.200000e+07

# Malumotlarni modelga tayyorlash

In [ ]:
from sklearn.model_selection import train_test_split
train_set, test_set = train_test_split(df, test_size=0.2, random_state=42)

X_train = train_set.drop(["price"], axis=1)
y = train_set["price"].copy()

X_num = X_train.drop(['location',"district"], axis=1)

In [ ]:
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OrdinalEncoder, StandardScaler

num_pipeline = Pipeline([
      ('imputer',SimpleImputer(strategy='median')),
      ('std_scaler',StandardScaler())
])

In [ ]:
num_pipeline.fit_transform(X_num)

array([[-0.57746118, -0.03810144, -0.31266907, -0.78950544],
       [ 1.25131698,  0.06793816, -0.75864437, -0.40330378],
       [-1.49185026, -0.04831267, -0.75864437, -0.40330378],
       ...,
       [-0.57746118, -0.04045788, -1.20461968, -1.1757071 ],
       [-0.57746118, -0.03181762, -0.31266907, -0.78950544],
       [ 0.3369279 , -0.0066823 , -0.75864437,  1.14150286]])

In [ ]:
median = y.median()
y = y.fillna(median)

In [ ]:
from sklearn.compose import ColumnTransformer

num_attribs = list(X_num)
cat_attribs = ["location","district"]

full_pipeline = ColumnTransformer([
    ('num',num_pipeline, num_attribs),
    ('cat',OrdinalEncoder(),cat_attribs)
])


In [ ]:
X_prepared = full_pipeline.fit_transform(X_train)

In [ ]:
X_prepared

array([[-5.77461178e-01, -3.81014438e-02, -3.12669070e-01,
        -7.89505443e-01,  6.39000000e+02,  5.00000000e+00],
       [ 1.25131698e+00,  6.79381642e-02, -7.58644373e-01,
        -4.03303783e-01,  2.19000000e+02,  2.00000000e+00],
       [-1.49185026e+00, -4.83126653e-02, -7.58644373e-01,
        -4.03303783e-01,  1.15800000e+03,  9.00000000e+00],
       ...,
       [-5.77461178e-01, -4.04578795e-02, -1.20461968e+00,
        -1.17570710e+00,  7.80000000e+02,  6.00000000e+00],
       [-5.77461178e-01, -3.18176152e-02, -3.12669070e-01,
        -7.89505443e-01,  9.10000000e+02,  7.00000000e+00],
       [ 3.36927898e-01, -6.68230066e-03, -7.58644373e-01,
         1.14150286e+00,  9.42000000e+02,  7.00000000e+00]])

# Model yaratish

In [ ]:
from sklearn.linear_model import LinearRegression

LR_model = LinearRegression()

In [ ]:
LR_model.fit(X_prepared,y)

LinearRegression()

# Modelni baholash

In [ ]:
X_test = test_set.drop(['price'],axis=1)
X_test

location           district  \
132   город Ташкент, Чиланзарский район, Чиланзар 6-...       Чиланзарский   
3771  город Ташкент, Сергелийский район, Сергели-I Я...       Сергелийский   
65    город Ташкент, Учтепинский район, Чиланзар 15-...        Учтепинский   
7525  город Ташкент, Шайхантахурский район, Алишера ...    Шайхантахурский   
6791          город Ташкент, Мирабадский район, Чимкент        Мирабадский   
...                                                 ...                ...   
4834      город Ташкент, Чиланзарский район, Чиланзар-9       Чиланзарский   
3125  город Ташкент, Мирзо-Улугбекский район, ц-1 Бу...  Мирзо-Улугбекский   
347      город Ташкент, Яшнободский район, Фергана Йули        Яшнободский   
6678  город Ташкент, Сергелийский район, Массив серг...       Сергелийский   
333   город Ташкент, Чиланзарский район, Чиланзар 7-...       Чиланзарский   

      rooms   size  level  max_levels  
132       2   37.0      1           4  
3771      1   39.0      5           5  
65        4  110.0      3           3  
7525      4   84.0      2           4  
6791      4  100.0      3           4  
...     ...    ...    ...         ...  
4834      2   50.0      2           5  
3125      4   92.0      4           4  
347       2   59.0      4           4  
6678      3   57.0      3           7  
333       2   58.0      1           9  

[1513 rows x 6 columns]

In [ ]:
y_test = test_set['price'].copy()

In [ ]:
X_test_prepared = full_pipeline.fit_transform(X_test)
median = y_test.median()
y_test = y_test.fillna(median)

In [ ]:
X_test_prepared

array([[-5.73375710e-01, -5.91500534e-02, -1.21458600e+00,
        -7.44232141e-01,  3.04000000e+02,  6.00000000e+00],
       [-1.52564514e+00, -5.82206386e-02,  5.90146252e-01,
        -3.74680704e-01,  2.08000000e+02,  4.00000000e+00],
       [ 1.33116315e+00, -2.52264145e-02, -3.12219872e-01,
        -1.11378358e+00,  2.34000000e+02,  5.00000000e+00],
       ...,
       [-5.73375710e-01, -4.89264910e-02,  1.38963190e-01,
        -7.44232141e-01,  5.66000000e+02,  1.10000000e+01],
       [ 3.78893719e-01, -4.98559057e-02, -3.12219872e-01,
         3.64422171e-01,  2.04000000e+02,  4.00000000e+00],
       [-5.73375710e-01, -4.93911983e-02, -1.21458600e+00,
         1.10352505e+00,  3.05000000e+02,  6.00000000e+00]])

In [ ]:
y_predict = LR_model.predict(X_test_prepared)

In [ ]:
from sklearn.metrics import mean_squared_error
lin_mse = mean_squared_error(y_test,y_predict)

lin_rmse = np.sqrt(lin_mse)
print(lin_rmse)

240542.67310807278


# Saqlab qo'yish

In [ ]:
import joblib

filename = 'LR_model.jbl'
joblib.dump(LR_model,filename)

['LR_model.jbl']